/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Universidad_Grupo3.Vistas;

import Universidad_Grupo3.AccesoADatos.InscripcionData;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Universidad_Grupo3.AccesoADatos.MateriaData;
import Universidad_Grupo3.Entidades.Alumno;
import Universidad_Grupo3.Entidades.Materia;
import java.util.ArrayList;
import java.util.Vector;

/**
 *
 * @author Hollmann
 */
public class Consultas extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();

    public Consultas() {
        initComponents();
        armarCabecera();
        llenarCombo();
        limpiarCampo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlSeleccione = new javax.swing.JLabel();
        jcMateria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAlumno = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlTitulo.setText("Listado de Alumnos por Materia");

        jlSeleccione.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlSeleccione.setText("Seleccione una materia:");

        jcMateria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcMateriaActionPerformed(evt);
            }
        });

        jtaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Apellido", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jtaAlumno);

        jbSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSalir)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(224, 224, 224)
                            .addComponent(jlTitulo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(106, 106, 106)
                            .addComponent(jlSeleccione)
                            .addGap(205, 205, 205)
                            .addComponent(jcMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jlTitulo)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSeleccione)
                    .addComponent(jcMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Combobox
    private void jcMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMateriaActionPerformed
        // TODO add your handling code here:

        InscripcionData inscripcionData = new InscripcionData();
        Materia materia = (Materia) jcMateria.getSelectedItem();

        List<Alumno> alumnos = inscripcionData.obtenerAlumnosXMateria(materia.getIdMateria());

        if (alumnos == null) {
            System.out.println("La lista de alumnos es nula.");
        } else {
            System.out.println("La lista de alumnos tiene " + alumnos.size() + " elementos.");
        }
        llenarLista(alumnos);

    }//GEN-LAST:event_jcMateriaActionPerformed

    //Boton salir
    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void llenarCombo() {
        MateriaData materiaData = new MateriaData();

        List<Materia> materias = materiaData.listarMaterias();
        if (materias != null) {
            for (Materia materia : materias) {
                System.out.println("Materias del combo :"+materia);
                jcMateria.addItem(materia);
            }
        }
    }

    private void limpiarCampo() {
        if (jcMateria != null) {
            jcMateria.setSelectedIndex(-1);
        }
    }

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("DNI");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        jtaAlumno.setModel(modelo);
    }

    private void borrarLista() {
        int filas = modelo.getRowCount() - 1;
        if (filas > 0) {
            for (int i = filas; i >= 0; i--) {
                modelo.removeRow(i);
            }
            jtaAlumno.repaint();
        }
    }

    private void llenarLista(List<Alumno> alumnos) {
        borrarLista();
        if (alumnos != null) {
            for (Alumno alumno : alumnos) {
                System.out.println(alumno);
                Vector<Object> renglon = new Vector<>();
                renglon.add(alumno.getIdAlumno());
                renglon.add(alumno.getDni());
                renglon.add(alumno.getApellido());
                renglon.add(alumno.getNombre());

                modelo.addRow(renglon);
            }
            jtaAlumno.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Materia> jcMateria;
    private javax.swing.JLabel jlSeleccione;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtaAlumno;
    // End of variables declaration//GEN-END:variables
}
